export const flowers = [
    {
        id: 1, 
        name: "Red Roses",
        image: "/Image/ge 2026-04-19 at 3.52.53 AM.jpeg",
        category: "Roses",
        price: 100, 

    },
    {   
        id: 2,  
        name: "Red Roses",
        image: "/Image/Image 2026-04-19 at 3.52.53 AM.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 3, 
        name: "Red Roses",
        image:"/Image/WhatsApp Image 2026-04-19 at 3.52.51 AM.jpeg",
        category: "Roses",
             price: 120,


    },  

   {   
        id: 4,  
        name: "Red Roses",
        image: "/Image/WhatsApp Image 2026-04-19 at 3.52.52 AM.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 5,  
        name: "Red Roses",
        image: "/Image/WhatsApp Image 2026-04-19 at 3.52.53 AM.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 6,  
        name: "White Roses",
        image: "/Image/white1.jpeg",
        category: "Roses",
        price: 150,
    },
    {   
        id: 7,  
        name: "White Roses",
       image: "/Image/white2.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 8,  
        name: "White Roses",
       image: "/Image/white3.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 9,  
        name: "White Roses",
        image: "/Image/White5.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 10,  
        name: "White Roses",
        image: "/Image/White4.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 11,  
        name: "White Roses",
        image: "/Image/White5.jpeg",
        category: "Roses",
        price: 150, 
    },
    {   
        id: 12,  
        name: "Wedding Bouquet",
        image: "/Image/wedding1.jpeg",
        category: "Wedding",
        price: 150, 
    },
     {   
        id: 13,  
        name: "Wedding Bouquet",
        image: "/Image/wedding2.jpeg",
        category: "Wedding",
        price: 150, 
    },
     {   
        id: 14,  
        name: "Wedding Bouquet",
        image: "/Image/wedding3.jpeg",
        category: "Wedding",
        price: 150, 
    },
     {   
        id: 15,  
        name: "Wedding Bouquet",
        image: "/Image/wedding4.jpeg",
        category: "Wedding",
        price: 150, 
    },
     {   
        id: 16,  
        name: "Birthday Bouquet",
        image: "/Image/birthday1.jpeg",
        category: "Birthday",
        price: 150, 
    },
     {   
        id: 17,  
        name: "Birthday Bouquet",
        image: "/Image/birthday2.jpeg",
        category: "Birthday",
        price: 150, 
    },
     {   
        id: 18,  
        name: "Birthday Bouquet",
        image: "/Image/br3.jpeg",
        category: "Birthday",
        price: 150, 
    },
     {   
        id: 19,  
        name: "Birthday Bouquet",
        image: "/Image/br4.jpeg",
        category: "Birthday",
        price: 150, 
    },
     {   
        id: 20,  
        name: "Sunflower Bouquet",
        image: "/Image/sun1.jpeg",
        category: "Sunflowers",
        price: 150, 
    },
     {   
        id: 21,  
        name: "Sunflower Bouquet",
        image: "/Image/sun2.jpeg",
        category: "Sunflowers",
        price: 150, 
    },
     {   
        id: 22,  
        name: "Sunflower Bouquet",
        image: "/Image/sun3.jpeg",
        category: "Sunflowers",
        price: 150, 
    },
     {   
        id: 23,  
        name: "Sunflower Bouquet",
        image: "/Image/sun4.jpeg",
        category: "Sunflowers",
        price: 150, 
    },
     {   
        id: 24  ,  
        name: "Sunflower Bouquet",
        image: "/Image/sun4.jpeg",
        category: "Sunflowers",
        price: 150, 
    },
     {   
        id: 25,  
        name: "Moonlight Bouquet",
        image: "/Image/ll1.jpeg",
        category: "Lilies",
        price: 150,     },
     {   
        id: 26  ,  
        name: "Moonlight Bouquet",
        image: "/Image/ll2.jpeg",
        category: "Lilies",
        price: 150, 
    },
     {   
        id: 27,  
        name: "Moonlight Bouquet",
        image: "/Image/ll3.jpeg",
        category: "Lilies",
        price: 150, 
    },
     {   
        id: 28  ,  
        name: "Moonlight Bouquet",
        image: "/Image/ll4.jpeg",
        category: "Lilies",
        price: 150, 
    },
     {   
        id: 29,  
        name: "Moonlight Bouquet",
        image: "/Image/ll5.jpeg",
        category: "Lilies",
        price: 150, 
    },
      {   
        id: 30,  
        name: "Daisy Bouquet",
        image: "/Image/ds1.jpeg",
        category: "Daisies",
        price: 150, 
    },
      {   
        id: 31,  
        name: "Daisy Bouquet",
        image: "/Image/ds2.jpeg",
        category: "Daisies",
        price: 150, 
    },
      {   
        id: 32,  
        name: "Daisy Bouquet",
        image: "/Image/ds3.jpeg",
        category: "Daisies",
        price: 150, 
    },

]

export default flowers